# Generated by Django 4.0.6 on 2022-09-29 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_comments_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(choices=[('editor', 'editor'), ('reader', 'reader')], default='reader', max_length=128),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('urgent', 'urgent'), ('primary', 'primary'), ('secondary', 'secondary')], default='secondary', max_length=128),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('To do', 'To do'), ('doing', 'doing'), ('done', 'done')], default='To do', max_length=128),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tag',
            field=models.CharField(choices=[('Not view', 'Not view'), ('View', 'View'), ('Fix', 'Fix')], default='Not view', max_length=128),
        ),
        migrations.AlterField(
            model_name='project',
            name='typ',
            field=models.CharField(choices=[('dev', 'dev'), ('model', 'model'), ('word', 'word')], default='dev', max_length=128),
        ),
    ]
